http_exceptions/__init__.py,sha256=kQ7lQLrjx90t-AVXKUU9OhTNU2IKLsg9krUK8Gz9yRg,2440
http_exceptions/client_exceptions.py,sha256=TM8iHEJB3NWrbOS6CIzoG2ccP6VFjcz8kHk7HhLkyGk,9046
http_exceptions/http_exception.py,sha256=FKBIZpcSHFHhWsvKOPHHggy5uUDG5188pdYqM2M7XPY,924
http_exceptions/py.typed,sha256=dHaMYeog-n6iNI7LusnkAs74dFFA91AqOP7_KoQtpik,54
http_exceptions/server_exceptions.py,sha256=HDqmUMU96eOcAH-CDwni3KKcQKYEhgdGTAatVCi_4aY,3783
http_exceptions-0.0.6.dist-info/METADATA,sha256=B0nu1RVnxAriqnwTLT40GYBmnzxsGeyb7nkgJfbLSds,3358
http_exceptions-0.0.6.dist-info/WHEEL,sha256=ewwEueio1C2XeHTvT17n8dZUJgOvyCWCt0WVNLClP9o,92
http_exceptions-0.0.6.dist-info/top_level.txt,sha256=nCsOu8w0eKykZ5L75RPpbMclcCQvAnVxrTtT26W_xiM,16
http_exceptions-0.0.6.dist-info/RECORD,,
