http_exceptions/__init__.py,sha256=Nai7OIWeWB2I05kuQtttbuxmAOQKk4LgK12hT0WSUTs,2440
http_exceptions/client_exceptions.py,sha256=vahvxVK_gAz3ZJVyUKiKirLblGMtDRlUwRu39vAsHLI,9220
http_exceptions/http_exception.py,sha256=Rtx03Xrrhv-wuz5xl67cFvfjd9l9Yb8EMVUt_xqJFf4,1774
http_exceptions/py.typed,sha256=dHaMYeog-n6iNI7LusnkAs74dFFA91AqOP7_KoQtpik,54
http_exceptions/server_exceptions.py,sha256=976ovITDC8sV7DVlZjA8XLdByP3E7Nfr-CpbtpcOjZE,3849
http_exceptions-0.1.0.dist-info/METADATA,sha256=1SzZv4UqTXToZKUm56ZlDVoudQYoUCdmReU8tEyJzt0,3406
http_exceptions-0.1.0.dist-info/WHEEL,sha256=ewwEueio1C2XeHTvT17n8dZUJgOvyCWCt0WVNLClP9o,92
http_exceptions-0.1.0.dist-info/top_level.txt,sha256=nCsOu8w0eKykZ5L75RPpbMclcCQvAnVxrTtT26W_xiM,16
http_exceptions-0.1.0.dist-info/RECORD,,
